Update patch set 8
Patch Set 8:

Error: Package: ansible-2.4.1.0-1.el7.noarch (extras)
           Requires: python-setuptools
Error: Package: opstools-ansible-0.1.0-5.el7.noarch (temp)
           Requires: python-setuptools
 You could try using --skip-broken to work around the problem

I still have no idea, why python-setuptools can not be found.

Patch-set: 8
Label: Code-Review=0